cmd/chantools/closepoolaccount.go
cmd/chantools/doublespendinputs.go
cmd/chantools/recoverloopin.go
cmd/chantools/rescuefunding.go
cmd/chantools/root.go
cmd/chantools/sweepremoteclosed.go
cmd/chantools/sweeptimelock.go
cmd/chantools/sweeptimelockmanual.go
cmd/chantools/zombierecovery_makeoffer.go
doc/chantools.md
doc/chantools_closepoolaccount.md
doc/chantools_doublespendinputs.md
doc/chantools_recoverloopin.md
doc/chantools_rescuefunding.md
doc/chantools_sweepremoteclosed.md
doc/chantools_sweeptimelock.md
doc/chantools_sweeptimelockmanual.md
doc/chantools_zombierecovery_makeoffer.md
lnd/signer.go

This PR adds a new command to the chantools tool which allows
users to RBF inputs. In case a channel opening transaction is stuck
in the mempool, this command can be used to RBF spend the inputs
of the channel opening transaction to a different address.
I tested it by spinning up two nodes and funding a channel between them with one p2wkh
and one p2tr input. I then ran the command to replace the opening tx.

Add rbfinputs command

---

cmd/chantools/sweeptimelock.go
cmd/chantools/sweeptimelockmanual.go
cmd/chantools/sweeptimelockmanual_test.go
lnd/chanbackup.go

Instead of needing to manually dump the channel backup file, look for
the remote revocation base point and then have the CSV delay and channel
derivation index being brute forced, we can extract all that info
directly from the channel backup file.
This should save a lot of time for doing unnecessary brute force iterations.

sweeptimelockmanual: allow specifying the backup file directly

---

cmd/chantools/sweepremoteclosed.go
lnd/hdkeychain.go

Fixes https://github.com/lightninglabs/chantools/issues/105.
Adds support for `SIMPLE_TAPROOT` channels to `sweepremoteclosed`.

sweepremoteclosed: add support for simple taproot channels

---

README.md
cmd/chantools/pullanchor.go
cmd/chantools/root.go
doc/chantools.md
doc/chantools_pullanchor.md
lnd/signer.go

Allows users to pull down (CPFP) an anchor output of a channel force close transaction that has a too low fee.
Example use:
```
chantools pullanchor \
--sponsorinput <txid:vout> \        # must be an input from lncli listunspent that is confirmed and has enough funds to pay for fees
--anchoraddr bc1q... \        # this is the on-chain address of the anchor output (the one with 330 satoshis)
--changeaddr bc1q... \        # this is a p2wkh address from your lnd wallet where the change goes to (lncli newaddress p2wkh)
--feerate xx        # the desired fee rate in sat/vByte, must be high enough to sponsor both transactions, so must be higher than the "effective" fee rate currently is
```

multi: add new pullanchor command

---

cmd/chantools/pullanchor.go

Tiny bugfix where we would not account for all anchor amounts calculating the feerate.

pullanchor: account for all anchor outputs.

---

btc/explorer_api.go
btc/summary.go
cmd/chantools/closepoolaccount.go
cmd/chantools/doublespendinputs.go
cmd/chantools/forceclose.go
cmd/chantools/pullanchor.go
cmd/chantools/recoverloopin.go
cmd/chantools/rescuefunding.go
cmd/chantools/root.go
cmd/chantools/summary.go
cmd/chantools/sweepremoteclosed.go
cmd/chantools/sweeptimelock.go
cmd/chantools/sweeptimelockmanual.go
cmd/chantools/triggerforceclose.go
cmd/chantools/zombierecovery_findmatches.go
doc/chantools.md
doc/chantools_closepoolaccount.md
doc/chantools_doublespendinputs.md
doc/chantools_pullanchor.md
doc/chantools_recoverloopin.md
doc/chantools_rescuefunding.md
doc/chantools_sweepremoteclosed.md
doc/chantools_sweeptimelock.md
doc/chantools_sweeptimelockmanual.md
lnd/hdkeychain.go

With this PR we add P2TR address support to each command that requires the user to specify a sweep or change address.
The user now also has the option to specify `fromseed` as the value for the address in which case a new P2WKH address is derived from the seed directly.

Support P2TR as sweep/change address everywhere

---

README.md
cmd/chantools/root.go
cmd/chantools/zombierecovery_makeoffer.go
cmd/chantools/zombierecovery_preparekeys.go

This PR adds two new flags to the zombierecovery workflow that are needed for nodes with a large number of channels.

zombierecovery: add --matchonly flag to makeoffer, --numkeys to preparekeys

---

cmd/chantools/doublespendinputs.go
doc/chantools_doublespendinputs.md
doc/chantools_fakechanbackup.md
doc/chantools_recoverloopin.md
doc/chantools_zombierecovery_makeoffer.md
doc/chantools_zombierecovery_preparekeys.md

`doublespendinputs` is designed to replace transactions, those new transactions should also be replacable by default.

doublespendinputs: allow RBF per default

---

cmd/chantools/zombierecovery_makeoffer.go

Was fixed after a node-runner reached out with the following stack trace:
Helping someone after a crash :
"I use chantools version v0.12.1 for the recovery of 2 channels with the command:"
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x316d0c]
goroutine 1 [running]:
github.com/btcsuite/btcd/txscript.NewTxSigHashes(0x4000127998, {0x11057a0, 0x4000186188})
github.com/btcsuite/btcd@v0.23.5-0.20230905170901-80f5a0ffdf36/txscript/hashcache.go:243 +0x12c
github.com/lightninglabs/chantools/lnd.(*Signer).AddPartialSignature(0x0?, 0x4000127a18, {{0x2312ba5?, 0x13dea5f?}, 0x400056b680?}, 0x40000486e0, {0x4000586d70, 0x47, 0x47}, 0x0)
github.com/lightninglabs/chantools/lnd/signer.go:154 +0x78 …
```

Fix Partial Signature Signing.

---

README.md
cmd/chantools/root.go
cmd/chantools/signmessage.go
doc/chantools_signmessage.md
go.mod
go.sum

This commit adds the signmessage command which allows a user to sign a message with the nodes identity key, similiar to `lncli signmessage`.

signmessage: add signmessage cmd

---

cmd/chantools/signpsbt.go
lnd/signer.go

Fixes signing PSBTs with P2WKH inputs.

signpsbt+lnd: fix signing for P2WKH

---

README.md
cmd/chantools/root.go
cmd/chantools/triggerforceclose.go
doc/chantools.md
doc/chantools_deletepayments.md
doc/chantools_dropchannelgraph.md
doc/chantools_dropgraphzombies.md
doc/chantools_migratedb.md
doc/chantools_recoverloopin.md
doc/chantools_removechannel.md
doc/chantools_triggerforceclose.md

Fixes https://github.com/lightninglabs/chantools/issues/60.
This PR makes the `triggerforceclose` compatible with all node types (not just some specific version of CLN), so it can be used to ask any peer to initiate a force close of a channel.
We also add Tor support for the command.

triggerforceclose: make compatible with all nodes, add Tor support

---

.gitignore

Gitignores IntelliJ `.idea` folders.

gitignore: .idea folder

---

cmd/chantools/signpsbt.go

This commit fixes an issue where the signpsbt sub command was only able to sign for a single input.
To avoid attempting to double sign an input that already has a partial signature, we also add a check instead of erroring out.

signpsbt: allow signing multiple inputs

---

btc/explorer_api.go

Fixes the bug that if a force close output has multiple outputs but only some of them are unspent that the `sweepremoteclosed` command would attempt to sweep all of them.

btc: filter address outputs, only return unspent

---

.golangci.yml
cmd/chantools/zombierecovery_findmatches.go
cmd/chantools/zombierecovery_makeoffer.go
cmd/chantools/zombierecovery_makeoffer_test.go
cmd/chantools/zombierecovery_preparekeys.go
cmd/chantools/zombierecovery_signoffer.go
go.mod
go.sum
lnd/channel.go
lnd/channel_test.go

Fixes https://github.com/lightninglabs/chantools/issues/133.

zombierecovery: support MuSig2 to rescue Simple Taproot channels

---

cmd/chantools/root.go
cmd/chantools/sweeptimelockmanual.go
cmd/chantools/sweeptimelockmanual_test.go

Fixes a refactor issue that parsed the wrong address.

Fix sweeptimelockmanual, bump version to v0.13.3

---

README.md
cmd/chantools/root.go
doc/chantools_closepoolaccount.md
doc/chantools_doublespendinputs.md
doc/chantools_fakechanbackup.md
doc/chantools_forceclose.md
doc/chantools_pullanchor.md
doc/chantools_recoverloopin.md
doc/chantools_rescuefunding.md
doc/chantools_summary.md
doc/chantools_sweepremoteclosed.md
doc/chantools_sweeptimelock.md
doc/chantools_sweeptimelockmanual.md
doc/chantools_triggerforceclose.md
doc/chantools_zombierecovery_findmatches.md

The blockstream API is too unstable or blocks users after too few requests. This commit changes the default API server to api.node-recovery.com (hosted by guggero).

root+doc: change default API server to api.node-recovery.com

---

go.mod
go.sum

A tag was modified, leading to security errors with the `loop/swapserverrpc` dependency.

mod: fix swapserverrpc version with wrong tag

---

cmd/chantools/derivekey.go
cmd/chantools/derivekey_test.go
lnd/hdkeychain.go

Now it is possible to derive a public key from xpub if `--neuter` is passed:
```
chantools derivekey --rootkey xpub... --path "m/0/0" --neuter
```
Example:
```
$ chantools derivekey --testnet --rootkey tpubDDfTBtwwqxXuCej7pKYfbXeCW3inAtv1cw4knmvYTTHkw3NoKaeCNH5XdY6n6fnBPc1gWEgeurfmBVzJLfBB1hGU64LsHFzJv4ASqaHyALH --path "m/0/0" --neuter
2025-01-09 15:33:00.047 [INF] CHAN: chantools version v0.13.5 commit 
Path:                           m/0/0
Network:                        testnet3
Master Fingerprint:             dfe0654d
Public key:                     0280a3fcbeb7f770af6dd45cb0f4d02e1044eafe0d8b05bcaec79dc0478c7fa0da
Extended public key (xpub):     tpubDGveUteHeiGeoiYFcusMzsUZzEwhdT6jEG3Xuz7GXeV3QRchMoMb1dfGMkaLFn7uvQqMiUKkRwtS7d3r1CmhqGHuUpZ5ZgWuo2zNZsgLbg9
Address: …
```

derivekey: support xpubs in addition to xprvs

---

cmd/chantools/rescueclosed.go
cmd/chantools/root.go
cmd/chantools/summary.go
cmd/chantools/sweepremoteclosed.go
cmd/chantools/sweepremoteclosed_ancient.json
cmd/chantools/sweepremoteclosed_test.go
dataformat/summary.go
doc/chantools_forceclose.md
doc/chantools_rescueclosed.md
doc/chantools_summary.md
doc/chantools_sweeptimelock.md
doc/chantools_sweeptimelockmanual.md

LNBIG was kind enough to supply us with all the commit points of all the channels they force closed on their nodes over the years. This will allow users to sweep those channels using `chantools sweepremoteclosed` with just the seed. Previously those funds wouldn't have been recoverable because they would've required the LNBIG nodes to still be online to send over the `per_commit_point`.
There are 2454 unspent outputs in such channel force close transactions with a total of 10 BTC.

sweepremoteclosed: add commit points for ancient channels of LNBIG

---

README.md
cln/signer.go
cmd/chantools/sweepremoteclosed.go
cmd/chantools/triggerforceclose.go
cmd/chantools/zombierecovery_findmatches.go
doc/chantools_sweepremoteclosed.md
doc/chantools_triggerforceclose.md
lnd/hdkeychain.go
lnd/signer.go

Makes the `sweepremoteclosed` and `triggerforceclose` commands compatible with CLN.
Make sure to supply all peer public keys as a comma separated list to the `sweepremoteclosed` command with the `--peers` command line flag!

CLN: Make sweepremoteclosed and triggerforceclose CLN compatible
